name: Run JMH Benchmarks

on: 
  push:
    branches: 
      - master
  
jobs:
  runJmh:
    runs-on: ubuntu-latest
    # JMB TODO: find a way to limit the ability of rando forks to publish
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
      - name: run
        # jmh options:
        #  -f (fork) = 1: run each benchmark in a forked process, once
        run: >
          RELEASE_VERSION=snapshot ./gradlew jmhJar && 
          java -jar build/libs/graphql-java-snapshot-jmh.jar 
          -f 1
