name: Run JMH Benchmarks

on: 
  push:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      benchmarks_to_run:
        description: >
          Space-separated list of name patterns of benchmarks that should be run. 
          Examples:"IntMap", "AddError ListBenchmark"
          If blank, all tests will be run.
        required: false
        # JMB TODO: tidy
        default: AddError ListBenchmark
  
jobs:
  runJmh:
    runs-on: ubuntu-latest
    # JMB TODO: find a way to limit the ability of rando forks to publish
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: run
        # jmh options:
        #  -f (fork) = 1: run each benchmark in a forked process, once
        #  -rf (result format) json: return json output
        #  -rff (result format file) results.json: write output to results.json
        #  Arg : run classes that match the specified pattern
        run: >
          RELEASE_VERSION=snapshot ./gradlew --no-daemon jmhJar && 
          java -jar build/libs/graphql-java-snapshot-jmh.jar 
          -f 1
          -rf json
          -rff results.json
          ${{ github.events.inputs.benchmarks_to_run }}
