name: Run JMH Benchmarks

on: 
  push:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      benchmarks_to_run:
        description: >
          Comma-separated regex of benchmark names (either class or method names work) that should be run. 
          Examples:"IntMap", "Int.*,Bench.*"
          If blank, all tests will be run.
        required: false
  
jobs:
  runJmh:
    if: github.repository == 'graphql-java/graphql-java'
    runs-on: ubuntu-latest
    # JMB TODO: find a way to limit the ability of rando forks to publish
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: gcp auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: run
        # jmh options:
        #  -f (fork) = 1: run each benchmark in a forked process, once
        #  -rf (result format) json: return json output
        #  -rff (result format file) results.json: write output to results.json
        #  Arg : run classes that match the specified pattern
        #
        # JMB TODO
        # "${{ github.events.inputs.benchmarks_to_run }}"
        # AddError
        run: >
          RELEASE_VERSION=snapshot ./gradlew --no-daemon jmhJar && 
          java -jar build/libs/graphql-java-snapshot-jmh.jar 
          -f 1
          -rf json
          -rff results.json
          "${{ github.events.inputs.benchmarks_to_run }}"

      - name: post-results
        run: |
          ROWS_FILE=$(.github/workflows/pack-jmh-result.sh graphql-java ./results.json)
          bq --dataset_id=gj-perf:test_results load --source_format=NEWLINE_DELIMITED_JSON runs "$ROWS_FILE"
